//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BcuApiDotNet.uy.gub.bcu.cotizaciones {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsbcucotizacionesSoapBinding", Namespace="Cotiza")]
    public partial class wsbcucotizaciones : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsbcucotizaciones() {
            this.Url = global::BcuApiDotNet.Properties.Settings.Default.BcuApiDotNet_uy_gub_bcu_cotizaciones_wsbcucotizaciones;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Cotizaaction/AWSBCUCOTIZACIONES.Execute", RequestElementName="wsbcucotizaciones.Execute", RequestNamespace="Cotiza", ResponseElementName="wsbcucotizaciones.ExecuteResponse", ResponseNamespace="Cotiza", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Salida")]
        public wsbcucotizacionesout Execute(wsbcucotizacionesin Entrada) {
            object[] results = this.Invoke("Execute", new object[] {
                        Entrada});
            return ((wsbcucotizacionesout)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(wsbcucotizacionesin Entrada) {
            this.ExecuteAsync(Entrada, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(wsbcucotizacionesin Entrada, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Entrada}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Cotiza")]
    public partial class wsbcucotizacionesin {
        
        private short[] monedaField;
        
        private System.Nullable<System.DateTime> fechaDesdeField;
        
        private System.Nullable<System.DateTime> fechaHastaField;
        
        private sbyte grupoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public short[] Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> FechaDesde {
            get {
                return this.fechaDesdeField;
            }
            set {
                this.fechaDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> FechaHasta {
            get {
                return this.fechaHastaField;
            }
            set {
                this.fechaHastaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datoscotizaciones.dato", Namespace="Cotiza")]
    public partial class datoscotizacionesdato {
        
        private System.Nullable<System.DateTime> fechaField;
        
        private short monedaField;
        
        private string nombreField;
        
        private string codigoISOField;
        
        private string emisorField;
        
        private double tCCField;
        
        private double tCVField;
        
        private double arbActField;
        
        private sbyte formaArbitrarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public short Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoISO {
            get {
                return this.codigoISOField;
            }
            set {
                this.codigoISOField = value;
            }
        }
        
        /// <remarks/>
        public string Emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        public double TCC {
            get {
                return this.tCCField;
            }
            set {
                this.tCCField = value;
            }
        }
        
        /// <remarks/>
        public double TCV {
            get {
                return this.tCVField;
            }
            set {
                this.tCVField = value;
            }
        }
        
        /// <remarks/>
        public double ArbAct {
            get {
                return this.arbActField;
            }
            set {
                this.arbActField = value;
            }
        }
        
        /// <remarks/>
        public sbyte FormaArbitrar {
            get {
                return this.formaArbitrarField;
            }
            set {
                this.formaArbitrarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Cotiza")]
    public partial class respuestastatus {
        
        private sbyte statusField;
        
        private short codigoerrorField;
        
        private string mensajeField;
        
        /// <remarks/>
        public sbyte status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public short codigoerror {
            get {
                return this.codigoerrorField;
            }
            set {
                this.codigoerrorField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Cotiza")]
    public partial class wsbcucotizacionesout {
        
        private respuestastatus respuestastatusField;
        
        private datoscotizacionesdato[] datoscotizacionesField;
        
        /// <remarks/>
        public respuestastatus respuestastatus {
            get {
                return this.respuestastatusField;
            }
            set {
                this.respuestastatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public datoscotizacionesdato[] datoscotizaciones {
            get {
                return this.datoscotizacionesField;
            }
            set {
                this.datoscotizacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsbcucotizacionesout Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsbcucotizacionesout)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591