namespace BcuApiDotNet {
    public enum CodigoError: short {
        MENSAJE_VACIO = 0,
        NO_EXISTE_COTIZACION_PARA_FECHA_INDICADA = 100,
        CODIGO_MONEDA_NO_EXISTE = 101,
        FECHA_INVALIDA = 102,
        FECHA_HASTA_MENOR_QUE_FECHA_DESDE = 103,
        RANGO_FECHAS_EXCESIVO = 104,
        GRUPO_NO_EXISTE_O_INHABILITADO = 105,
        SERVICIO_NO_DISPONIBLE_POR_ACTUALIZACION = 106,
        SERVICIO_NO_DISPONIBLE = 107,
    }
}
